### ISSUE TITLE
Run scripts do not have executable flag set post-install

### ISSUE THREAD

**Issue by wzfe** [winepress/homebrew-winepress#1]
/usr/local/bin

-rw-r--r--  1 wzfe  admin  225 Jan  7 19:45 tesla-sunflower

**Comment by wzfe** [comment]
Actually it is also setting the user to the "admin" group, which is wrong.

**Comment by Garland220** [comment]
https://github.com/winepress/homebrew-winepress/commit/5f3727766af91f305162229b4e88d96ed25e3e5e
