### ISSUE TITLE
lastone-razor: script does not enter executable directory successfully, due to spaces

### ISSUE THREAD

**Issue by wzfe** [winepress/homebrew-winepress#19]
% brew press install lastone-razor
==> Downloading https://files.scene.org/get:nl-http/parties/2003/equinoxe03/intro/razor_1911__demo_division-las
###### ################################################################## 100.0%

==> Verifying checksum for Cask lastone-razor
🍺  lastone-razor staged at '/opt/homebrew-winepress/winepress/lastone-razor/1' (5 files, 84K)
(master) % lastone-razor
/usr/local/bin/lastone-razor: line 4: cd: /opt/homebrew-winepress/winepress/lastone-razor/1/Razor: No such file or directory

/usr/local/bin/lastone-razor
# !/bin/sh

export WINEPREFIX=/opt/homebrew-winepress/winepress/lastone-razor/1/prefix
export WINEDEBUG=-all
cd /opt/homebrew-winepress/winepress/lastone-razor/1/Razor 1911  Demo Division - Last One
wine last_one.exe &>/dev/null

**Comment by wzfe** [comment]
Related to #17 presumably

**Comment by Garland220** [comment]
https://github.com/winepress/homebrew-winepress/commit/25a22768116280c03e5efed670a62e61bb5dc115

should fix

**Comment by wzfe** [comment]
Confirmed...
