### ISSUE TITLE
"brew press zap" and "brew press uninstall" do not delete run script(s)

### ISSUE THREAD

**Issue by wzfe** [winepress/homebrew-winepress#2]
/usr/local/bin

(master) [1] % brew press zap tesla-sunflower 
==> Implied "brew cask uninstall tesla-sunflower"
Warning: No zap stanza present for Cask 'tesla-sunflower'
==> Removing all staged versions of Cask 'tesla-sunflower'
(master) % ls -la tes*
-rw-r--r--  1 z  admin  225 Jan  7 19:45 tesla-sunflower

**Comment by Garland220** [comment]
https://github.com/winepress/homebrew-winepress/commit/c0b4ca21a60350b0f1d464b27956be78edd9e560
