### ISSUE TITLE
can install with 'brew cask' –– with errors

### ISSUE THREAD

**Issue by wzfe** [winepress/homebrew-winepress#3]
(master) % brew cask install tesla-sunflower
Warning: Unexpected method 'win_exe' called on Cask tesla-sunflower.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

```
  brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

  If this doesn’t fix the problem, please report this bug:

```
  https://github.com/caskroom/homebrew-cask#reporting-bugs
```

Warning: Unexpected method 'wine_version' called on Cask tesla-sunflower.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

```
  brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

  If this doesn’t fix the problem, please report this bug:

```
  https://github.com/caskroom/homebrew-cask#reporting-bugs
```

Warning: Unexpected method 'wine_arch' called on Cask tesla-sunflower.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

```
  brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

  If this doesn’t fix the problem, please report this bug:

```
  https://github.com/caskroom/homebrew-cask#reporting-bugs
```

Warning: Unexpected method 'wine_tricks' called on Cask tesla-sunflower.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

```
  brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

  If this doesn’t fix the problem, please report this bug:

```
  https://github.com/caskroom/homebrew-cask#reporting-bugs
```

==> Satisfying dependencies
complete
==> Downloading https://files.scene.org/get:nl-http/demos/groups/sunflower/tesla_sunflower.zip
Already downloaded: /Library/Caches/Homebrew/tesla-sunflower-1.zip
==> Verifying checksum for Cask tesla-sunflower
🍺  tesla-sunflower staged at '/opt/homebrew-cask/Caskroom/tesla-sunflower/1' (6 files, 7.7M)

**Comment by wzfe** [comment]
Cask should not know about winepress, let alone allow us to install Presses(?) into /opt/homebrew-cask/

**Comment by Garland220** [comment]
https://github.com/winepress/homebrew-winepress/commit/a6240895ebdc817b93ad5534bde9a7d96872fa77
