### ISSUE TITLE
support magnet: links

### ISSUE THREAD

**Issue by wzfe** [winepress/homebrew-winepress#7]
We have (at least) two options for this through homebrew, `transmission` and `aria2`. I prefer `aria2` because it is quite lightweight and supports a lot of different protocols, including metalink and bittorrent.

**Comment by wzfe** [comment]
Test with this Cas...err... Grape:

https://github.com/winepress/homebrew-winepress/blob/master/Grapes/zuma-deluxe.rb

**Comment by wzfe** [comment]
NAME
       aria2c - The ultra fast download utility

SYNOPSIS
       aria2c [<OPTIONS>] [<URI>|<MAGNET>|<TORRENT_FILE>|<METALINK_FILE>] ...

DESCRIPTION
       aria2  is  a  utility for downloading files. The supported protocols are HTTP(S), FTP, SFTP,
       BitTorrent, and Metalink. aria2 can download a  file  from  multiple  sources/protocols  and
       tries  to  utilize  your  maximum  download  bandwidth.  It supports downloading a file from
       HTTP(S)/FTP /SFTP  and  BitTorrent  at  the  same  time,  while  the  data  downloaded  from
       HTTP(S)/FTP/SFTP  is uploaded to the BitTorrent swarm. Using Metalink chunk checksums, aria2
       automatically validates chunks of data while downloading a file.

OPTIONS
       NOTE:
          Most FTP related options are applicable to SFTP as well.  Some options are not  effective
          against SFTP (e.g., --ftp-pasv)

   Basic Options
       -d, --dir=<DIR> The directory to store the downloaded file.

**Comment by Garland220** [comment]
https://github.com/winepress/homebrew-winepress/commit/721906eec979922a4a2ba0e182901070eb7e1cc6
https://github.com/winepress/homebrew-winepress/commit/e69ce126b0ead9e8d4f513f96d8cf8f5ed35ab09
https://github.com/winepress/homebrew-winepress/commit/d5431b2428fdb8b3fd6fdb5da7dbce3c5f9332fb
